# Generated by Django 4.2.7 on 2023-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0008_alter_rootobject_self_contenttype'),
        ('apis_ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collection',
            field=models.ManyToManyField(to='apis_metainfo.collection'),
        ),
        migrations.AddField(
            model_name='function',
            name='collection',
            field=models.ManyToManyField(to='apis_metainfo.collection'),
        ),
        migrations.AddField(
            model_name='institution',
            name='collection',
            field=models.ManyToManyField(to='apis_metainfo.collection'),
        ),
        migrations.AddField(
            model_name='person',
            name='collection',
            field=models.ManyToManyField(to='apis_metainfo.collection'),
        ),
        migrations.AddField(
            model_name='place',
            name='collection',
            field=models.ManyToManyField(to='apis_metainfo.collection'),
        ),
        migrations.AddField(
            model_name='salary',
            name='collection',
            field=models.ManyToManyField(to='apis_metainfo.collection'),
        ),
    ]
