# Generated by Django 4.2.7 on 2023-11-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0002_event_collection_function_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='function',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
