# Generated by Django 4.2.7 on 2023-11-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0004_alter_event_metadata_alter_function_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='metadata',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
