# Generated by Django 4.2.10 on 2024-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0011_alter_rootobject_deprecated_name'),
        ('apis_ontology', '0006_event_name_function_name_institution_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='collection',
            field=models.ManyToManyField(editable=False, to='apis_metainfo.collection'),
        ),
        migrations.AlterField(
            model_name='function',
            name='collection',
            field=models.ManyToManyField(editable=False, to='apis_metainfo.collection'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='collection',
            field=models.ManyToManyField(editable=False, to='apis_metainfo.collection'),
        ),
        migrations.AlterField(
            model_name='person',
            name='collection',
            field=models.ManyToManyField(editable=False, to='apis_metainfo.collection'),
        ),
        migrations.AlterField(
            model_name='place',
            name='collection',
            field=models.ManyToManyField(editable=False, to='apis_metainfo.collection'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='collection',
            field=models.ManyToManyField(editable=False, to='apis_metainfo.collection'),
        ),
    ]
