# Generated by Django 4.2.10 on 2024-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0007_alter_event_collection_alter_function_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alternative_label',
            field=models.TextField(blank=True, help_text='Feld um alternative Namen anzugeben.', null=True, verbose_name='Alternative Namen'),
        ),
    ]
