# Generated by Django 4.2.13 on 2024-05-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0009_versionevent_versionfunction_versioninstitution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionfunction_collection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='versionfunction_collection',
            name='function',
        ),
        migrations.RemoveField(
            model_name='versionfunction_collection',
            name='history',
        ),
        migrations.RemoveField(
            model_name='versioninstitution_collection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='versioninstitution_collection',
            name='history',
        ),
        migrations.RemoveField(
            model_name='versioninstitution_collection',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='versionperson_collection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='versionperson_collection',
            name='history',
        ),
        migrations.RemoveField(
            model_name='versionperson_collection',
            name='person',
        ),
        migrations.RemoveField(
            model_name='versionplace_collection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='versionplace_collection',
            name='history',
        ),
        migrations.RemoveField(
            model_name='versionplace_collection',
            name='place',
        ),
        migrations.RemoveField(
            model_name='versionsalary_collection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='versionsalary_collection',
            name='history',
        ),
        migrations.RemoveField(
            model_name='versionsalary_collection',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='event',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='function',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='person',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='place',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='collection',
        ),
        migrations.DeleteModel(
            name='VersionEvent_collection',
        ),
        migrations.DeleteModel(
            name='VersionFunction_collection',
        ),
        migrations.DeleteModel(
            name='VersionInstitution_collection',
        ),
        migrations.DeleteModel(
            name='VersionPerson_collection',
        ),
        migrations.DeleteModel(
            name='VersionPlace_collection',
        ),
        migrations.DeleteModel(
            name='VersionSalary_collection',
        ),
    ]
