# Generated by Django 4.2.13 on 2024-07-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
        ('apis_ontology', '0010_remove_versionfunction_collection_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgeuebt_in',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ausgeübt in',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Besitzt',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'besitzt',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Bewohnt',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'bewohnt',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Buergt_fuer',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'bürgt für',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Empfiehlt',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'empfiehlt',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Findet_statt_in',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'findet statt in',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Fuehrt_durch',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'führt durch',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Gehoert_zu',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'gehört zu',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ging_hervor_aus',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ging hervor aus',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Haelt_sich_auf_in',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'hält sich auf in',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Hat_ehe_mit',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'hat Ehe mit',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Hat_familienbeziehung_zu',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'hat Familienbeziehung zu',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Hat_geschaeftsbeziehung_zu',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'hat Geschäftsbeziehung zu',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Hat_heimatort_in',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'hat Heimatort in',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Hat_korrespondenz_mit',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'hat Korrespondenz mit',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Hat_streit_mit',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'hat Streit mit',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_bruder_schwester_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist Bruder/Schwester von',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_geboren_in',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist geboren in',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_gelegen_in',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist gelegen in',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_gestorben_in',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist gestorben in',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_im_dienst_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist im Dienst von',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_kind_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist Kind von',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_mitglied_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist Mitglied von',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_moeglicherweise_identisch_mit',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist möglicherweise identisch mit',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_moeglicherweise_spezifiziert_als',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist möglicherweise spezifiziert als',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_pfruendner_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist Pfründner von',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_taetig_an',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist tätig an',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_taetig_in',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist tätig in',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_teil_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist Teil von',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_untergeordnet',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist untergeordnet',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_verbunden_mit',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist verbunden mit',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_verpfaendet_an',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist verpfändet an',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Ist_vormund_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'ist Vormund von',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Nimmt_entgegen',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'nimmt entgegen',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Nimmt_teil_an',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'nimmt teil an',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Steht_in_verbindung_mit',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'steht in Verbindung mit',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Verkauft_besitz_an',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'verkauft Besitz an',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Weist_an',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'weist an',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Wird_angewiesen_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'wird angewiesen von',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Wird_ausbezahlt_an',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'wird ausbezahlt an',
            },
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Wird_ausgeuebt_von',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            options={
                'verbose_name': 'wird ausgeübt von',
            },
            bases=('relations.relation',),
        ),
    ]
