# Generated by Django 4.2.10 on 2024-03-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0010_businessrelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessrelation",
            name="notes",
        ),
    ]
