# Generated by Django 5.0.7 on 2024-09-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0011_alter_event_options_alter_function_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['label']},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='versionplace',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versionplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versionplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
