# Generated by Django 4.2.10 on 2024-03-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0001_initial"),
        ("apis_ontology", "0011_remove_businessrelation_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentOf",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
            ],
            bases=("relations.relation",),
        ),
    ]
