# Generated by Django 4.2.13 on 2024-08-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0011_ausgeuebt_in_besitzt_bewohnt_buergt_fuer_empfiehlt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='nimmt_teil_an',
            name='foo',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='apis_ontology.person'),
            preserve_default=False,
        ),
    ]
