# Generated by Django 5.1.5 on 2025-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0014_ausgeuebtin_besitzt_bewohnt_buergtfuer_empfiehlt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionevent',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versionfunction',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versioninstitution',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versionplace',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versionsalary',
            name='self_contenttype',
        ),
        migrations.AddField(
            model_name='place',
            name='feature_code',
            field=models.CharField(blank=True, default='', help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>', max_length=16),
        ),
        migrations.AddField(
            model_name='versionplace',
            name='feature_code',
            field=models.CharField(blank=True, default='', help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>', max_length=16),
        ),
    ]
