# Generated by Django 5.1.7 on 2025-06-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0015_remove_versionevent_self_contenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='feature_code',
            field=models.CharField(blank=True, default='', help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>', max_length=16, verbose_name='feature code'),
        ),
        migrations.AlterField(
            model_name='place',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='versionplace',
            name='feature_code',
            field=models.CharField(blank=True, default='', help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>', max_length=16, verbose_name='feature code'),
        ),
        migrations.AlterField(
            model_name='versionplace',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='versionplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='versionplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
