# Generated by Django 5.1.7 on 2025-07-08 07:09

import django.db.models.deletion
import django_interval.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0016_alter_place_feature_code_alter_place_label_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunktionFuehrtDurch',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
                ('start', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('end', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_to', models.DateField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('relations.relation', models.Model),
        ),
        migrations.CreateModel(
            name='FunktionNimmtEntgegen',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
                ('start', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('end', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_to', models.DateField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('relations.relation', models.Model),
        ),
        migrations.CreateModel(
            name='VersionFunktionFuehrtDurch',
            fields=[
                ('relation_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='relations.relation')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('subj_object_id', models.PositiveIntegerField()),
                ('obj_object_id', models.PositiveIntegerField()),
                ('start', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('end', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obj_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('subj_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'historical funktion fuehrt durch',
                'verbose_name_plural': 'historical funktion fuehrt durchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VersionFunktionNimmtEntgegen',
            fields=[
                ('relation_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='relations.relation')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('subj_object_id', models.PositiveIntegerField()),
                ('obj_object_id', models.PositiveIntegerField()),
                ('start', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('end', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('start_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('end_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obj_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('subj_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'historical funktion nimmt entgegen',
                'verbose_name_plural': 'historical funktion nimmt entgegens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
