# Generated by Django 5.2.9 on 2026-01-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0018_remove_versionausgeuebtin_version_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausgeuebtin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='besitzt',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='bewohnt',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='buergtfuer',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='empfiehlt',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='findetstattin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='fuehrtdurch',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='funktionfuehrtdurch',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='funktionnimmtentgegen',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='gehoertzu',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='ginghervoraus',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='haeltsichaufin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='hatehemit',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='hatfamilienbeziehungzu',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='hatgeschaeftsbeziehungzu',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='hatheimatortin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='hatkorrespondenzmit',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='hatstreitmit',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='institutionfuehrtdurch',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='institutionweistan',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istan',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istbruderschwestervon',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istgeborenin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istgelegenin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istgestorbenin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istimdienstvon',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istkindvon',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istmitgliedvon',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istmoeglicherweiseidentischmit',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istmoeglicherweisespezifiziertals',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istpfruendnervon',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='isttaetigan',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='isttaetigin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istteilvon',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istuntergeordnet',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istverbundenmit',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istverpfaendetan',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='istvormundvon',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='nimmtentgegen',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='nimmtteilan',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='personweistan',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='stehtinverbindungmit',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='verkauftbesitzan',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='wirdangewiesenvon',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='wirdausbezahltanfunction',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='wirdausbezahltanperson',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='wirdausgeuebtvon',
            options={'ordering': ['pk']},
        ),
    ]
